import SwiftUI
import Foundation

struct AAIEventData {
   @ObservedObject var userModel = UserViewModel.shared
   
    static let eventNames = [
//      "Debug",
      "AWS Cloud Essentials for Business Leaders",
      "AWS Cloud Essentials for Business Leaders – Financial Services",
      "AWS Cloud Practitioner Essentials",
      "AWS Technical Essentials",
      "AWS Security Essentials",
      "Architecting on AWS",
      "AWS Cloud Financial Management for Builders",
      "AWS Cloud for Finance Professionals",
      "AWS Security Best Practices",
      "AWS Security Governance at Scale",
      "AWS Well-Architected Best Practices",
      "Advanced AWS Well-Architected Best Practices",
//      "Big Data on AWS",
      "Building Batch Data Analytics Solutions on AWS",
      "Building Data Analytics Solutions Using Amazon Redshift",
      "Building Data Lakes on AWS",
      "Building Streaming Data Analytics on AWS",
//      "Cloud Operations on AWS",
//      "Data Warehousing on AWS",
//      "Deep Learning on AWS",
      "Developing on AWS",
//      "Developing Serverless Solutions on AWS",
//      "DevOps Engineering on AWS",
//      "Migrating to AWS",
//      "MLOps Engineering on AWS",
//      "Planning and Designing Databases on AWS",
//      "Practical Data Science with Amazon SageMaker",
//      "Running Containers on Amazon Elastic Kubernetes Service",
//      "Security Engineering on AWS",
//      "The Machine Learning Pipeline on AWS",
//      "Video Streaming Essentials for AWS Media Services",
      "Advanced Architecting on AWS",
      "Advanced Developing on AWS",
//      "Architecting on AWS - Accelerator",
//      "Amazon SageMaker Studio for Data Scientists",
//      "Authoring Visual Analytics Using Amazon QuickSight",
    ]
    
    static let eventSequences: [String: [(name: String, duration: Int)]] = [
      "Debug": [("Debug - Module 0", 20), ("Debug - Module 1", 45)],
      
      "AWS Cloud Essentials for Business Leaders": [
          ("ACEBL - Module 1: Course Introductions", 10),
          ("ACEBL - Module 2: Information Technology for Business Transformation", 10),
          ("ACEBL - Module 3: Cloud Computing", 45),
          ("ACEBL - ☕️🍎 Break", 15),
          ("ACEBL - Module 4: Business Value of the Cloud", 45),
          ("ACEBL - Module 5: The Cloud Value Framework", 45),
          ("ACEBL - Module 6: Business Value Activity", 15),
          ("ACEBL - 🙋‍♀️❓🙋‍♂️ Q&A", 30),
      ],
      
      "AWS Cloud Essentials for Business Leaders – Financial Services": [
          ("ACEBL-Fin - Module 1: Course Introductions", 10),
          ("ACEBL-Fin - Module 2: Information Technology for Business Transformation", 10),
          ("ACEBL-Fin - Module 3: Cloud Computing", 45),
          ("ACEBL-Fin - ☕️🍎 Break", 15),
          ("ACEBL-Fin - Module 4: Business Value of the Cloud", 45),
          ("ACEBL-Fin - Module 5: The Cloud Value Framework", 45),
          ("ACEBL-Fin - Module 6: Business Value Activity", 15),
          ("ACEBL-Fin - 🙋‍♀️❓🙋‍♂️ Q&A", 30),
      ],
      
      "AWS Security Best Practices": [
          ("ASBP - Module 0: Course and Student Introductions", 15),
          ("ASBP - Module 1: Security Overview", 45),
          ("ASBP - ☕️🍎 Break", 10),
          ("ASBP - Module 2: Securing the Network", 30),
          ("ASBP - 🔬🛠️ Lab 1: Controlling the Network", 45),
          ("ASBP - 🍴🍲🥝 Lunch", 60),
          ("ASBP - Module 3: Amazon EC2 Security", 50),
          ("ASBP - ☕️🍎 Break", 10),
          ("ASBP - 🔬🛠️ Lab 2: Securing the Endpoint", 60),
          ("ASBP - ☕️🍎 Break", 10),
          ("ASBP - Module 4: Monitoring and Alerting", 50),
          ("ASBP - ☕️🍎 Break", 10),
          ("ASBP - 🔬🛠️ Lab 3: Security Monitoring", 45),
          ("ASBP - Module 5: Course Conclusion", 10),
          ("ASBP - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      
      "AWS Security Governance at Scale": [
          ("ASGS - Module 0: Course and Student Introductions", 30),
          ("ASGS - Module 1: Governance at scale", 30),
          ("ASGS - ☕️🍎 Break", 10),
          ("ASGS - Module 2: Governance Automation", 50),
          ("ASGS - ☕️🍎 Break", 10),
          ("ASGS - Flex time for trainer - Questions/Demos/Deep Dive", 50),
          ("ASGS - 🍴🍲🥝 Lunch", 60),
          ("ASGS - Module 3: Preventive Controls", 45),
          ("ASGS - 🔬🛠️ Lab 1: Deploy Resources on AWS Service Catalog", 40),
          ("ASGS - ☕️🍎 Break", 10),
          ("ASGS - Module 4: Detective Controls", 40),
          ("ASGS - 🔬🛠️ Lab 2: Taking action with AWS Systems Manager", 40),
          ("ASGS - ☕️🍎 Break", 10),
          ("ASGS - 🔬🛠️ Lab 3: Compliance and Security Automation w/AWS Config", 40),
          ("ASGS - Module 5: Resources", 15),
          ("ASGS - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      
      "AWS Well-Architected Best Practices": [
          ("AWABP - Module 0: Course Introduction", 20),
          ("AWABP - Module 1: Well-Architected Introduction", 20),
          ("AWABP - Module 2: Operational Excellence", 20),
          ("AWABP - ☕️🍎 Break", 10),
          ("AWABP - 🔬🛠️ Lab 1: Operational Excellence", 60),
          ("AWABP - Module 3: Reliability", 20),
          ("AWABP - ☕️🍎 Break", 10),
          ("AWABP - 🔬🛠️ Lab 2: Reliability", 70),
          ("AWABP - 🍴🍲🥝 Lunch", 60),
          ("AWABP - Module 4: Security", 20),
          ("AWABP - 🔬🛠️ Lab 3: Security", 60),
          ("AWABP - Module 5: Performance Efficiency", 20),
          ("AWABP - ☕️🍎 Break", 10),
          ("AWABP - 🔬🛠️ Lab 4: Performance Efficiency", 40),
          ("AWABP - Module 6: Cost Optimization", 20),
          ("AWABP - ☕️🍎 Break", 10),
          ("AWABP - 🔬🛠️ Lab 5: Cost Optimization", 90),
          ("AWABP - Module 7: Sustainability", 10),
          ("AWABP - Module 8: Course Summary", 10),
          ("AWABP - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      
      
      "Advanced AWS Well-Architected Best Practices": [
          ("AAWABP - Module 0: Course and Student Introductions", 20),
          ("AAWABP - Module 1: AWS Well-Architected Framework Reviews", 50),
          ("AAWABP - ☕️🍎 Break", 15),
          ("AAWABP - Module 2: Customer scenario group sessions", 150),
          ("AAWABP - 🍴🍲🥝 Lunch break", 60),
          ("AAWABP - Module 3: Risk solutions and priorities", 120),
          ("AAWABP - Module 4: Resources", 30),
          ("AAWABP - ☕️🍎 Break", 15),
          ("AAWABP - Module 5: Course summary", 15),
          ("AAWABP - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      "Building Batch Data Analytics Solutions on AWS": [
          ("BBDASA - Module 0: Course overview and introductions", 20),
          ("BBDASA - Module A: Overview of data analytics and the data pipeline", 15),
          ("BBDASA - Module 1: Using Amazon Redshift in the data analytics pipeline", 15),
          ("BBDASA - ☕️🍎 Break", 10),
          ("BBDASA - Module 2: Introduction to Amazon Redshift", 15),
          ("BBDASA - 🔬🛠️ Lab 1: Load and query data in an Amazon Redshift cluster", 40),
          ("BBDASA - ☕️🍎 Break", 10),
          ("BBDASA - Module 3: Ingestion and storage", 45),
          ("BBDASA - 🍴🍲🥝 Lunch", 60),
          ("BBDASA - 🔬🛠️ Lab 2: Data analytics using Amazon Redshift Spectrum", 45),
          ("BBDASA - Module 4: Processing and optimizing data (Part 1)", 20),
          ("BBDASA - 🔬🛠️ Lab 3: Data transformation and querying in Amazon Redshift", 45),
          ("BBDASA - ☕️🍎 Break", 10),
          ("BBDASA - Module 4: Processing and optimizing data (Part 2)", 35),
          ("BBDASA - Module 5: Security and monitoring of Amazon Redshift clusters", 30),
          ("BBDASA - ☕️🍎 Break", 10),
          ("BBDASA - Module 6: Designing data warehouse analytics solutions", 25),
          ("BBDASA - Module B: Developing modern data architectures on AWS", 15),
          ("BBDASA - Module C: Course wrap-up", 15),
          ("AAWABP - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      
      
      "AWS Cloud Financial Management for Builders": [
          ("ACFMB - Module 0: Course Overview", 30),
          ("ACFMB - Module 1: Introduction to Cloud Financial Management", 45),
          ("ACFMB - Module 2: Resource Tagging", 35),
          ("ACFMB - ☕️🍎 Break", 15),
          ("ACFMB - 🔬🛠️ Lab 1: Cost Optimization: Control Resource Consumption Using Tagging and AWS Config", 60),
          ("ACFMB - 🍴🍲🥝 Lunch", 60),
          ("ACFMB - Module 3: Pricing and Cost", 70),
          ("ACFMB - Module 4: AWS Billing, Reporting, and Monitoring", 60),
          ("ACFMB - ☕️🍎 Break", 15),
          ("ACFMB - 🔬🛠️ Lab 2: Cost Optimization: Deploy Ephemeral Environments Using Amazon EC2 Auto Scaling", 60),
          ("ACFMB - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",1),

          ("ACFMB - Day 1 Review", 30),
          ("ACFMB - Module 5: Architecting for Cost: Compute Part 1", 65),
          ("ACFMB - ☕️🍎 Break", 15),
          ("ACFMB - Module 5: Architecting for Cost: Compute Part 2", 65),
          ("ACFMB - 🔬🛠️ Lab 3: Cost Optimization: Right Size Amazon EC2 Instances Using Amazon CloudWatch Metrics", 60),
          ("ACFMB - 🍴🍲🥝 Lunch", 60),
          ("ACFMB - Module 6: Architecting for Cost: Networking", 60),
          ("ACFMB - ☕️🍎 Break", 15),
          ("ACFMB - 🔬🛠️ Lab 4: Cost Optimization: Reduce Data Transfer Costs Using Amazon CloudFront and Endpoints", 90),
          ("ACFMB - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",2),

          ("ACFMB - Day 2 Review", 30),
          ("ACFMB - Module 7: Architecting for Cost: Storage", 80),
          ("ACFMB - ☕️🍎 Break", 15),
          ("ACFMB - 🔬🛠️ Lab 5: Cost Optimization: Reduce Storage Costs Using Amazon S3 Lifecycle Management", 60),
          ("ACFMB - 🍴🍲🥝 Lunch", 60),
          ("ACFMB - Module 8: Architecting for Cost: Databases", 60),
          ("ACFMB - Module 9: Cost Governance", 90),
          ("ACFMB - ☕️🍎 Break", 15),
          ("ACFMB - 🔬🛠️ Lab 6: Cost Optimization: Reduce Compute Costs Using AWS Instance Scheduler", 60),
          ("ACFMB - Module 10: Course Summary", 15),
          ("ACFMB - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      "AWS Cloud for Finance Professionals": [
          ("ACFP - Course introduction", 30),
          ("ACFP - Module 1: Introduction (content)", 120),
          ("ACFP - ☕️🍎 Break", 15),
          ("ACFP - Activity 1.1: Cloud value metrics", 15),
          ("ACFP - Activity 1.2: Cloud Financial Management outcomes", 15),
          ("ACFP - 🍴🍲🥝 Lunch break", 60),
          ("ACFP - Module 2: Planning and Forecasting (content)", 70),
          ("ACFP - Activity 2.1: Build and refine a cost estimate", 20),
          ("ACFP - ☕️🍎 Break", 15),
          ("ACFP - Module 3: Measurement and Accountability (content)", 70),
          ("ACFP - Demo 3.1: Tools for cost visibility; tools for cost monitoring", 20),
          ("ACFP - 🙋‍♀️❓🙋‍♂️ Q&A", 30),
          ("nextDay",1),

          ("ACFP - Day 1 Review", 45),
          ("ACFP - Module 4: Cost Optimization (content)", 130),
          ("ACFP - Activity 4.1: Cost optimization", 15),
          ("ACFP - 🍴🍲🥝 Lunch break", 60),
          ("ACFP - Module 5: Cloud Financial Operations (content)", 90),
          ("ACFP - Activity 5.1: Organizational models", 15),
          ("ACFP - ☕️🍎 Break", 15),
          ("ACFP - Module 6: Financial Transformation and Innovation (content)", 60),
          ("ACFP - Activity 6.1: Solutions for financial innovation", 15),
          ("ACFP - Module 7: Resources and Next Steps (content)", 20),
          ("ACFP - 🙋‍♀️❓🙋‍♂️ Q&A", 30),
      ],

      "Building Data Analytics Solutions Using Amazon Redshift": [
          ("BDASUAR - Module 0: Course overview and introductions", 20),
          ("BDASUAR - Module A: Overview of data analytics and the data pipeline", 15),
          ("BDASUAR - Module 1: Using Amazon Redshift in the data analytics pipeline", 15),
          ("BDASUAR - ☕️🍎 Break", 10),
          ("BDASUAR - Module 2: Introduction to Amazon Redshift", 15),
          ("BDASUAR - 🔬🛠️ Lab 1: Load and query data in an Amazon Redshift cluster", 40),
          ("BDASUAR - ☕️🍎 Break", 10),
          ("BDASUAR - Module 3: Ingestion and storage", 45),
          ("BDASUAR - 🍴🍲🥝 Lunch", 60),
          ("BDASUAR - 🔬🛠️ Lab 2: Data analytics using Amazon Redshift Spectrum", 45),
          ("BDASUAR - Module 4: Processing and optimizing data (Part 1)", 20),
          ("BDASUAR - 🔬🛠️ Lab 3: Data transformation and querying in Amazon Redshift", 45),
          ("BDASUAR - ☕️🍎 Break", 10),
          ("BDASUAR - Module 4: Processing and optimizing data (Part 2)", 35),
          ("BDASUAR - Module 5: Security and monitoring of Amazon Redshift clusters", 30),
          ("BDASUAR - ☕️🍎 Break", 10),
          ("BDASUAR - Module 6: Designing data warehouse analytics solutions", 25),
          ("BDASUAR - Module B: Developing modern data architectures on AWS", 15),
          ("BDASUAR - Module C: Course wrap-up", 15),
          ("BDASUAR - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      "Building Data Lakes on AWS": [
          ("BDLA - Module 0: Course and student introductions", 15),
          ("BDLA - Module 1: Introduction to data lakes", 30),
          ("BDLA - Module 2: Data ingestion, cataloging and preparation", 50),
          ("BDLA - ☕️🍎 Break", 10),
          ("BDLA - Module 3: Building a data lake with AWS Lake Formation", 35),
          ("BDLA - 🔬🛠️ Lab 1: Build a data lake using AWS Lake Formation", 45),
          ("BDLA - 🍴🍲🥝 Lunch", 60),
          ("BDLA - Module 4: Data processing and analytics", 50),
          ("BDLA - ☕️🍎 Break", 10),
          ("BDLA - Module 5: Additional Lake Formation configurations", 40),
          ("BDLA - 🔬🛠️ Lab 2: Automate data lake creation using AWS Lake Formation blueprints", 45),
          ("BDLA - ☕️🍎 Break", 10),
          ("BDLA - Module 6: Modern data architectures on AWS", 45),
          ("BDLA - 🔬🛠️ Lab 3: Publishing and managing data product in AWS Lake Formation", 30),
          ("BDLA - Module 7: Architecture and Course review", 15),
          ("BDLA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      "Building Streaming Data Analytics on AWS": [
          ("BSDAA - Module 0: Course Overview and Student Introductions", 20),
          ("BSDAA - Module A: Overview of Data Analytics and the Data Pipeline", 15),
          ("BSDAA - Module 1: Using Streaming Services in the Data Analytics Pipeline", 15),
          ("BSDAA - ☕️🍎 Break", 10),
          ("BSDAA - Module 2: Introduction to AWS Streaming Services", 30),
          ("BSDAA - 🔬🛠️ Lab 1: Setting up a Streaming Delivery Pipeline with Amazon Kinesis", 25),
          ("BSDAA - Module 3: Using Amazon Kinesis for Real-time Data Analytics", 40),
          ("BSDAA - ☕️🍎 Break", 10),
          ("BSDAA - 🔬🛠️ Lab 2: Streaming analytics with Amazon Kinesis Data Analytics and Apache Flink", 45),
          ("BSDAA - 🍴🍲🥝 Lunch", 60),
          ("BSDAA - Module 4: Securing, Monitoring, and Optimizing Amazon Kinesis", 15),
          ("BSDAA - Module 5: Using Amazon MSK in Streaming Data Analytics Solutions", 35),
          ("BSDAA - 🔬🛠️ Lab 3: Introduction to Access Control with Managed Streaming for Apache Kafka", 20),
          ("BSDAA - Module 6: Securing, Monitoring, and Optimizing Amazon MSK", 30),
          ("BSDAA - ☕️🍎 Break", 10),
          ("BSDAA - 🔬🛠️ Lab 4: Amazon MSK Streaming Pipeline and Application Deployment", 45),
          ("BSDAA - Module 7: Designing Streaming Data Analytics Solutions", 35),
          ("BSDAA - Module B: Developing Modern Data Architectures on AWS", 10),
          ("BSDAA - Module C: Course wrap up", 10),
          ("BSDAA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      
      
      
      
      
      
      
      
      
      
      "AWS Cloud Practitioner Essentials": [
         ("CP - Welcome", 20),
         ("CP - Module 0: Course Introduction", 5),
         ("CP - Module 1: Introduction to Amazon Web Services", 30),
         ("CP - Module 2: Compute in the Cloud (Part 1)", 30),
         ("CP - ☕️🍎 Break", 15),
         ("CP - Module 2: Compute in the Cloud (Part 2)", 30),
         ("CP - Module 3: Global Infrastructure and Reliability", 25),
         ("CP - Module 4: Networking (Part 1)", 20),
         ("CP - 🍴🍲🥝 Lunch", 60),
         ("CP - Module 4: Networking (Part 2)", 15),
         ("CP - Module 5: Storage and Databases", 40),
         ("CP - Module 6: Security", 35),
         ("CP - ☕️🍎 Break", 10),
         ("CP - Module 7: Monitoring and Analytics", 20),
         ("CP - Module 8: Pricing and Support", 30),
         ("CP - Module 9: Migration and Innovation", 40),
         ("CP - Module 10: AWS Certified Cloud Practitioner Basics", 15),
         ("CP - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      "Architecting on AWS": [
         ("AoA - Module 0: Course Introduction", 30),
         ("AoA - Module 1: Architecting Fundamentals", 45),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - 🔬🛠️ Lab 1: Explore and interact with the AWS Management Console and AWS Command Line Interface", 35),
         ("AoA - Module 2: Account Security", 60),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - Module 3: Networking 1", 60),
         ("AoA - 🍴🍲🥝 Lunch", 60),
         ("AoA - Module 4: Compute", 75),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - 🔬🛠️ Lab 2: Build your Amazon VPC infrastructure", 45),
         ("AoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
         ("nextDay",1),
         
         ("AoA - Day 1 review", 10),
         ("AoA - Module 5: Storage", 70),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - Module 6: Database Services", 70),
         ("AoA - 🔬🛠️ Lab 3: Create a database layer in your Amazon VPC infrastructure", 45),
         ("AoA - 🍴🍲🥝 Lunch", 60),
         ("AoA - Module 7: Monitoring and Scaling", 70),
         ("AoA - 🔬🛠️ Lab 4: Configure high availability in your Amazon VPC", 45),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - Module 8: Automation", 30),
         ("AoA - Module 9: Containers", 40),
         ("AoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
         ("nextDay",2),
         
         ("AoA - Day 2 review", 10),
         ("AoA - Module 10: Networking 2", 45),
         ("AoA - Module 11: Serverless", 45),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - 🔬🛠️ Lab 5: Build a serverless architecture", 45),
         ("AoA - Module 12: Edge Services", 60),
         ("AoA - 🍴🍲🥝 Lunch", 60),
         ("AoA - 🔬🛠️ Lab 6: Configure an Amazon CloudFront distribution with an Amazon S3 origin", 60),
         ("AoA - Module 13: Backup and Recovery", 40),
         ("AoA - 🔬🛠️ Capstone lab: Build an AWS multi-tier architecture", 90),
         ("AoA - Module 14: Course Summary", 10),
         ("AoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      "AWS Technical Essentials": [
          ("TE - Module 0: Course and Student Introductions", 25),
          ("TE - Module 1: Introduction to Amazon Web Services", 40),
          ("TE - 🔬🛠️ Lab 1: Introduction to AWS Identity and Access Management (IAM)", 30),
          ("TE - ☕️🍎 Break", 15),
          ("TE - Module 2: AWS Compute", 35),
          ("TE - Module 3: AWS Networking", 35),
          ("TE - 🔬🛠️ Lab 2: Creating a VPC and launching a Web Application in an Amazon EC2 Instance", 30),
          ("TE - 🍴🍲🥝 Lunch", 60),
          ("TE - Module 4: AWS Storage", 35),
          ("TE - Module 5: Databases", 35),
          ("TE - ☕️🍎 Break", 15),
          ("TE - 🔬🛠️ Lab 3: Configure a Web Application to use an Amazon S3 bucket and DynamoDB table", 45),
          ("TE - Module 6: Monitoring, Load Balancing, and Scaling", 20),
          ("TE - ☕️🍎 Break", 15),
          ("TE - 🔬🛠️ Lab 4: Configure High Availability for your Application", 45),
          ("TE - Module 7: Course Summary", 5),
          ("TE - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      
      "AWS Security Essentials": [
          ("SE - Module 0: Course and Student Introductions", 20),
          ("SE - Module 1: Exploring the Security Pillar", 15),
          ("SE - Module 2: Responsibilities and Compliance", 45),
          ("SE - ☕️🍎 Break", 15),
          ("SE - Module 3: Identity and Access Management (IAM)", 45),
          ("SE - 🔬🛠️ Lab 1: Introduction to Security Policies", 45),
          ("SE - 🍴🍲🥝 Lunch", 60),
          ("SE - Module 4: Protecting Infrastructure and Data", 60),
          ("SE - 🔬🛠️ Lab 2: Securing VPC Resources with Security Groups", 45),
          ("SE - ☕️🍎 Break", 15),
          ("SE - Module 5: Detection and Incident Response", 45),
          ("SE - Module 6: Course Wrap-Up", 15),
      ],
      
      
      "Developing on AWS": [
          ("DoA - Module 01: Introduction to Developing on AWS", 25),
          ("DoA - Module 02: Building a Web Application on AWS", 15),
          ("DoA - Module 03: Getting Started with Development on AWS", 55),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - Module 04: Configuring Permissions for the Development Environment", 45),
          ("DoA - 🔬🛠️ Lab 01: Getting set up", 60),
          ("DoA - 🍴🍲🥝 Lunch", 60),
          ("DoA - Module 05: Storage options", 45),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - Module 06: Storing and Hosting Your Application", 60),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 02: Hosting a Static Website in Amazon S3", 60),
          ("DoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",1),
          
          ("DoA - Module 07: Database Options", 40),
          ("DoA - Module 08: Processing Database Transactions", 35),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 03: Experimenting with Amazon DynamoDB", 60),
          ("DoA - Module 09: Processing Your Application Logic", 75),
          ("DoA - 🍴🍲🥝 Lunch", 60),
          ("DoA - 🔬🛠️ Lab 04: Building AWS Lambda Functions", 60),
          ("DoA - Module 10: Managing the APIs", 45),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 05: Using API Gateway", 60),
          ("DoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",2),

          ("DoA - Module 11: An Approach to Building a Modern Application", 45),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - Module 12: Authenticating Your Application Users", 65),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 06: Authenticating Users with Amazon Cognito", 90),
          ("DoA - 🍴🍲🥝 Lunch", 60),
          ("DoA - Module 13: Deploying Your Application", 30),
          ("DoA - Module 14: Observing Your Application", 45),
          ("DoA - ☕️🍎 Break", 15),
          ("DoA - Module 15: Monitoring and Troubleshooting Your Application", 60),
          ("DoA - Module 16: Course Summary", 10),
          ("DoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      
      "Advanced Architecting on AWS": [
          ("AAoA - Module 0: Introductions and Course Overview", 30),
          ("AAoA - Module 1: Review Architecting Concepts", 40),
          ("AAoA - 🔬🛠️ Lab 1: Securing Amazon S3 VPC Endpoint Communications", 60),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 2: Single to Multiple Accounts", 35),
          ("AAoA - Module 3: Hybrid Connectivity", 45),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("AAoA - Module 4: Specialized Infrastructure", 30),
          ("AAoA - Module 5: Connecting Networks", 40),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - 🔬🛠️ Lab 2: Configuring AWS Transit Gateways", 60),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",1),

          ("AAoA - Introduction, poll, icebreaker", 10),
          ("AAoA - Module 6: Containers", 40),
          ("AAoA - 🔬🛠️ Lab 3: Application Deployment with Amazon EKS on Fargate", 90),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 7: Continuous Integration/Continuous Delivery (CI/CD)", 30),
          ("AAoA - Module 8: Architecting for high availability and DDoS protection", 55),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 9: Securing Data", 60),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("AAoA - Module 10: Large-Scale Data Stores", 55),
          ("AAoA - 🔬🛠️ Lab 4: Setting Up a Data Lake with Lake Formation", 60),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",2),

          ("AAoA - Introduction, poll, icebreaker", 10),
          ("AAoA - Module 11: Migrating Workloads", 45),
          ("AAoA - 🔬🛠️ Lab 5: Migrating an On-Premises NFS Share Using DataSync and Storage Gateway", 60),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 12: Optimizing Cost", 55),
          ("AAoA - Module 13: Architecting for the Edge", 45),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("AAoA - Review Online Course Supplement (OCS)", 20),
          ("AAoA - Module 14: Review Projects", 90),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      
      "Advanced Developing on AWS": [
          ("ADoA - Module 0: Course and Student Introductions", 30),
          ("ADoA - Module 1 - PT1: The Cloud Journey", 75),
          ("AAoA - ☕️🍎 Break", 15),
          ("ADoA - Module 1 - PT2: The Cloud Journey", 75),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("ADoA - 🔬🛠️ Lab 1: Deploy Your Monolith Application Using AWS Elastic Beanstalk", 90),
          ("AAoA - ☕️🍎 Break", 15),
          ("ADoA - Module 2: Gaining Agility", 90),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",1),

          ("ADoA - Module 3: Monolith to Micro-services", 120),
          ("AAoA - ☕️🍎 Break", 15),
          ("ADoA - 🔬🛠️ Lab 2: Using AWS Lambda to Develop Microservices", 90),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("ADoA - Module 4: Polyglot Persistence and Distributed Complexity", 120),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",2),

          ("ADoA - Module 5: Resilience and Scale", 60),
          ("ADoA - 🔬🛠️ Lab 3: Exploring the AWS Messaging Options", 60),
          ("AAoA - ☕️🍎 Break", 15),
          ("ADoA - Module 6: Security and Observability", 90),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("ADoA - 🔬🛠️ Lab 4: Developing Microservices on AWS", 120),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],


      

      
//      "Advanced Architecting on AWS": [("AAoA - Module 0", 20), ("AAoA - Module 1", 45), ("AAoA - Module 2", 20)],
//      "Developing on AWS": [("DoA - Module 0", 20), ("DoA - Module 1", 10), ("DoA - Module 2", 120)],
//      "Advanced Developing on AWS": [("ADoA - Module 0", 20), ("ADoA - Module 1", 10), ("ADoA - Module 2", 120)]
    ]
    
    static let timeZones: [TimeZoneInfo] = TimeZone.knownTimeZoneIdentifiers.sorted().map { TimeZoneInfo(identifier: $0) }
}
