import SwiftUI
import Foundation

struct AAIEventData {
   @ObservedObject var userModel = UserViewModel.shared
   
    static let eventNames = [
//      "Debug",
//      "AWS Cloud Essentials for Business Leaders",
//      "AWS Cloud Essentials for Business Leaders – Financial Services",
      "AWS Cloud Practitioner Essentials",
      "AWS Technical Essentials",
      "AWS Security Essentials",
      "Architecting on AWS",
//      "AWS Cloud Financial Management for Builders",
//      "AWS Cloud for Finance Professionals",
//      "AWS Security Best Practices",
//      "AWS Security Governance at Scale",
//      "AWS Well-Architected Best Practices",
//      "Advanced AWS Well-Architected Best Practices",
//      "Big Data on AWS",
//      "Building Batch Data Analytics Solutions on AWS",
//      "Building Data Analytics Solutions Using Amazon Redshift",
//      "Building Data Lakes on AWS",
//      "Building Streaming Data Analytics on AWS",
//      "Cloud Operations on AWS",
//      "Data Warehousing on AWS",
//      "Deep Learning on AWS",
      "Developing on AWS",
//      "Developing Serverless Solutions on AWS",
//      "DevOps Engineering on AWS",
//      "Migrating to AWS",
//      "MLOps Engineering on AWS",
//      "Planning and Designing Databases on AWS",
//      "Practical Data Science with Amazon SageMaker",
//      "Running Containers on Amazon Elastic Kubernetes Service",
//      "Security Engineering on AWS",
//      "The Machine Learning Pipeline on AWS",
//      "Video Streaming Essentials for AWS Media Services",
      "Advanced Architecting on AWS",
//      "Advanced Developing on AWS",
//      "Architecting on AWS - Accelerator",
//      "Amazon SageMaker Studio for Data Scientists",
//      "Authoring Visual Analytics Using Amazon QuickSight",
    ]
    
    static let eventSequences: [String: [(name: String, duration: Int)]] = [
      "Debug": [("Debug - Module 0", 20), ("Debug - Module 1", 45)],
      "AWS Cloud Practitioner Essentials": [
         ("CP - Welcome", 20),
         ("CP - Module 0: Course Introduction", 5),
         ("CP - Module 1: Introduction to Amazon Web Services", 30),
         ("CP - Module 2: Compute in the Cloud (Part 1)", 30),
         ("CP - ☕️🍎 Break", 15),
         ("CP - Module 2: Compute in the Cloud (Part 2)", 30),
         ("CP - Module 3: Global Infrastructure and Reliability", 25),
         ("CP - Module 4: Networking (Part 1)", 20),
         ("CP - 🍴🍲🥝 Lunch", 60),
         ("CP - Module 4: Networking (Part 2)", 15),
         ("CP - Module 5: Storage and Databases", 40),
         ("CP - Module 6: Security", 35),
         ("CP - ☕️🍎 Break", 10),
         ("CP - Module 7: Monitoring and Analytics", 20),
         ("CP - Module 8: Pricing and Support", 30),
         ("CP - Module 9: Migration and Innovation", 40),
         ("CP - Module 10: AWS Certified Cloud Practitioner Basics", 15),
         ("CP - 🙋‍♀️❓🙋‍♂️ Q&A", 30),
      ],
      "Architecting on AWS": [
         ("AoA - Module 0: Course Introduction", 30),
         ("AoA - Module 1: Architecting Fundamentals", 45),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - 🔬🛠️ Lab 1: Explore and interact with the AWS Management Console and AWS Command Line Interface", 35),
         ("AoA - Module 2: Account Security", 60),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - Module 3: Networking 1", 60),
         ("AoA - 🍴🍲🥝 Lunch", 60),
         ("AoA - Module 4: Compute", 75),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - 🔬🛠️ Lab 2: Build your Amazon VPC infrastructure", 45),
         ("AoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
         ("nextDay",1),
         
         ("AoA - Day 1 review", 10),
         ("AoA - Module 5: Storage", 70),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - Module 6: Database Services", 70),
         ("AoA - 🔬🛠️ Lab 3: Create a database layer in your Amazon VPC infrastructure", 45),
         ("AoA - 🍴🍲🥝 Lunch", 60),
         ("AoA - Module 7: Monitoring and Scaling", 70),
         ("AoA - 🔬🛠️ Lab 4: Configure high availability in your Amazon VPC", 45),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - Module 8: Automation", 30),
         ("AoA - Module 9: Containers", 40),
         ("AoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
         ("nextDay",2),
         
         ("AoA - Day 2 review", 10),
         ("AoA - Module 10: Networking 2", 45),
         ("AoA - Module 11: Serverless", 45),
         ("AoA - ☕️🍎 Break", 15),
         ("AoA - 🔬🛠️ Lab 5: Build a serverless architecture", 45),
         ("AoA - Module 12: Edge Services", 60),
         ("AoA - 🍴🍲🥝 Lunch", 60),
         ("AoA - 🔬🛠️ Lab 6: Configure an Amazon CloudFront distribution with an Amazon S3 origin", 60),
         ("AoA - Module 13: Backup and Recovery", 40),
         ("AoA - 🔬🛠️ Capstone lab: Build an AWS multi-tier architecture", 90),
         ("AoA - Module 14: Course Summary", 10),
         ("AoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      "AWS Technical Essentials": [
          ("TE - Module 0: Course and Student Introductions", 25),
          ("TE - Module 1: Introduction to Amazon Web Services", 40),
          ("TE - 🔬🛠️ Lab 1: Introduction to AWS Identity and Access Management (IAM)", 30),
          ("TE - ☕️🍎 Break", 15),
          ("TE - Module 2: AWS Compute", 35),
          ("TE - Module 3: AWS Networking", 35),
          ("TE - 🔬🛠️ Lab 2: Creating a VPC and launching a Web Application in an Amazon EC2 Instance", 30),
          ("TE - 🍴🍲🥝 Lunch", 60),
          ("TE - Module 4: AWS Storage", 35),
          ("TE - Module 5: Databases", 35),
          ("TE - ☕️🍎 Break", 15),
          ("TE - 🔬🛠️ Lab 3: Configure a Web Application to use an Amazon S3 bucket and DynamoDB table", 45),
          ("TE - Module 6: Monitoring, Load Balancing, and Scaling", 20),
          ("TE - ☕️🍎 Break", 15),
          ("TE - 🔬🛠️ Lab 4: Configure High Availability for your Application", 45),
          ("TE - Module 7: Course Summary", 5),
          ("TE - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      
      "AWS Security Essentials": [
          ("SE - Module 0: Course and Student Introductions", 20),
          ("SE - Module 1: Exploring the Security Pillar", 15),
          ("SE - Module 2: Responsibilities and Compliance", 45),
          ("SE - ☕️🍎 Break", 15),
          ("SE - Module 3: Identity and Access Management (IAM)", 45),
          ("SE - 🔬🛠️ Lab 1: Introduction to Security Policies", 45),
          ("SE - 🍴🍲🥝 Lunch", 60),
          ("SE - Module 4: Protecting Infrastructure and Data", 60),
          ("SE - 🔬🛠️ Lab 2: Securing VPC Resources with Security Groups", 45),
          ("SE - ☕️🍎 Break", 15),
          ("SE - Module 5: Detection and Incident Response", 45),
          ("SE - Module 6: Course Wrap-Up", 15),
      ],
      
      
      "Developing on AWS": [
          ("DoA - Module 01: Introduction to Developing on AWS", 25),
          ("DoA - Module 02: Building a Web Application on AWS", 15),
          ("DoA - Module 03: Getting Started with Development on AWS", 55),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - Module 04: Configuring Permissions for the Development Environment", 45),
          ("DoA - 🔬🛠️ Lab 01: Getting set up", 60),
          ("DoA - 🍴🍲🥝 Lunch", 60),
          ("DoA - Module 05: Storage options", 45),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - Module 06: Storing and Hosting Your Application", 60),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 02: Hosting a Static Website in Amazon S3", 60),
          ("DoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",1),
          
          ("DoA - Module 07: Database Options", 40),
          ("DoA - Module 08: Processing Database Transactions", 35),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 03: Experimenting with Amazon DynamoDB", 60),
          ("DoA - Module 09: Processing Your Application Logic", 75),
          ("DoA - 🍴🍲🥝 Lunch", 60),
          ("DoA - 🔬🛠️ Lab 04: Building AWS Lambda Functions", 60),
          ("DoA - Module 10: Managing the APIs", 45),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 05: Using API Gateway", 60),
          ("DoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",2),

          ("DoA - Module 11: An Approach to Building a Modern Application", 45),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - Module 12: Authenticating Your Application Users", 65),
          ("DoA - ☕️🍎 Break", 10),
          ("DoA - 🔬🛠️ Lab 06: Authenticating Users with Amazon Cognito", 90),
          ("DoA - 🍴🍲🥝 Lunch", 60),
          ("DoA - Module 13: Deploying Your Application", 30),
          ("DoA - Module 14: Observing Your Application", 45),
          ("DoA - ☕️🍎 Break", 15),
          ("DoA - Module 15: Monitoring and Troubleshooting Your Application", 60),
          ("DoA - Module 16: Course Summary", 0),
          ("DoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],
      
      
      "Advanced Architecting on AWS": [
          ("AAoA - Module 0: Introductions and Course Overview", 30),
          ("AAoA - Module 1: Review Architecting Concepts", 40),
          ("AAoA - 🔬🛠️ Lab 1: Securing Amazon S3 VPC Endpoint Communications", 60),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 2: Single to Multiple Accounts", 35),
          ("AAoA - Module 3: Hybrid Connectivity", 45),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("AAoA - Module 4: Specialized Infrastructure", 30),
          ("AAoA - Module 5: Connecting Networks", 40),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - 🔬🛠️ Lab 2: Configuring AWS Transit Gateways", 60),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",1),

          ("AAoA - Introduction, poll, icebreaker", 10),
          ("AAoA - Module 6: Containers", 40),
          ("AAoA - 🔬🛠️ Lab 3: Application Deployment with Amazon EKS on Fargate", 90),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 7: Continuous Integration/Continuous Delivery (CI/CD)", 30),
          ("AAoA - Module 8: Architecting for high availability and DDoS protection", 55),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 9: Securing Data", 60),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("AAoA - Module 10: Large-Scale Data Stores", 55),
          ("AAoA - 🔬🛠️ Lab 4: Setting Up a Data Lake with Lake Formation", 60),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
          ("nextDay",2),

          ("AAoA - Introduction, poll, icebreaker", 10),
          ("AAoA - Module 11: Migrating Workloads", 45),
          ("AAoA - 🔬🛠️ Lab 5: Migrating an On-Premises NFS Share Using DataSync and Storage Gateway", 60),
          ("AAoA - ☕️🍎 Break", 15),
          ("AAoA - Module 12: Optimizing Cost", 55),
          ("AAoA - Module 13: Architecting for the Edge", 45),
          ("AAoA - 🍴🍲🥝 Lunch", 60),
          ("AAoA - Review Online Course Supplement (OCS)", 20),
          ("AAoA - Module 14: Review Projects", 90),
          ("AAoA - 🙋‍♀️❓🙋‍♂️ Q&A", 15),
      ],

      

      
//      "Advanced Architecting on AWS": [("AAoA - Module 0", 20), ("AAoA - Module 1", 45), ("AAoA - Module 2", 20)],
//      "Developing on AWS": [("DoA - Module 0", 20), ("DoA - Module 1", 10), ("DoA - Module 2", 120)],
//      "Advanced Developing on AWS": [("ADoA - Module 0", 20), ("ADoA - Module 1", 10), ("ADoA - Module 2", 120)]
    ]
    
    static let timeZones: [TimeZoneInfo] = TimeZone.knownTimeZoneIdentifiers.sorted().map { TimeZoneInfo(identifier: $0) }
}
